### ISSUE TITLE
Getting Not able to resolve realm from the request path!

### ISSUE THREAD

**Issue by AasthaSethia** [czetsuya/spring-keycloak-multi-tenant#1]
After gettinf redirected to keycloak login page I keep on getting Not able to resolve realm from the request path! I do not understand why

**Comment by czetsuya** [comment]
Seems like you did not add /tenant to the path? See this class: https://github.com/czetsuya/spring-keycloak-multi-tenant/blob/master/src/main/java/com/czetsuyatech/config/PathBasedConfigResolver.java.

**Comment by AasthaSethia** [comment]
I did, like I said I have started my application also and after successful login via keycloak page I get this error

**Comment by czetsuya** [comment]
Did you follow the video in the blog article I've written? It could be the redirectUri. What's the URL that you have after you login?

**Comment by AasthaSethia** [comment]
yes, in keyclaok for valid redirect uri I have set *, for my app if I am securing the endpoint lovalhost:8081/tenant/branch1/user, this in MultitenantkeycloakAuthenticatinEntryPoint I have set it like this  String contextAwareLoginUri = request.getContextPath() + "/tenant/" + realm + "/*"

**Comment by czetsuya** [comment]
Have you tried running my project as is? Do you have your project in Github?

**Comment by AasthaSethia** [comment]
no my project isnt on github but this error comes because it processes /favicon.io url

**Comment by czetsuya** [comment]
I see. Normally, you don't need the favicon in a REST service. I believe it's safe to remove. You can also apply logic in this part of the code like don't check a particular set of resource or path.

**Comment by AasthaSethia** [comment]
in pathconfigurer I added a check   
String[] realms = path.substring(path.indexOf("://")).split("/");
            if(realms.length>3) {
                String realm = realms[4];  like this now I am getting 404 seems like you were correct it is not picking up the redirect url

**Comment by AasthaSethia** [comment]
I am adding my keycloak security config 



package com.example.demo.config;

import org.keycloak.adapters.KeycloakConfigResolver;
import org.keycloak.adapters.KeycloakDeployment;
import org.keycloak.adapters.KeycloakDeploymentBuilder;
import org.keycloak.adapters.OIDCHttpFacade;
import org.keycloak.adapters.spi.HttpFacade;
import org.keycloak.adapters.springboot.KeycloakSpringBootConfigResolver;
import org.keycloak.adapters.springsecurity.KeycloakConfiguration;
import org.keycloak.adapters.springsecurity.authentication.KeycloakAuthenticationProvider;
import org.keycloak.adapters.springsecurity.config.KeycloakWebSecurityConfigurerAdapter;
import org.keycloak.adapters.springsecurity.filter.KeycloakAuthenticatedActionsFilter;
import org.keycloak.adapters.springsecurity.filter.KeycloakAuthenticationProcessingFilter;
import org.keycloak.adapters.springsecurity.filter.KeycloakPreAuthActionsFilter;
import org.keycloak.adapters.springsecurity.filter.KeycloakSecurityContextRequestFilter;
import org.keycloak.representations.adapters.config.AdapterConfig;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.autoconfigure.condition.ConditionalOnMissingBean;
import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty;
import org.springframework.boot.web.servlet.FilterRegistrationBean;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.context.annotation.DependsOn;
import org.springframework.http.HttpMethod;
import org.springframework.security.config.annotation.authentication.builders.AuthenticationManagerBuilder;
import org.springframework.security.config.annotation.method.configuration.EnableGlobalMethodSecurity;
import org.springframework.security.config.annotation.web.builders.HttpSecurity;
import org.springframework.security.config.annotation.web.configuration.EnableWebSecurity;
import org.springframework.security.config.annotation.web.configurers.AbstractHttpConfigurer;
import org.springframework.security.config.http.SessionCreationPolicy;
import org.springframework.security.core.authority.mapping.SimpleAuthorityMapper;
import org.springframework.security.core.session.SessionRegistryImpl;
import org.springframework.security.web.AuthenticationEntryPoint;
import org.springframework.security.web.authentication.logout.LogoutFilter;
import org.springframework.security.web.authentication.preauth.x509.X509AuthenticationFilter;
import org.springframework.security.web.authentication.session.RegisterSessionAuthenticationStrategy;
import org.springframework.security.web.authentication.session.SessionAuthenticationStrategy;
import org.springframework.security.web.util.matcher.AntPathRequestMatcher;
import org.springframework.web.cors.CorsConfiguration;
import org.springframework.web.cors.CorsConfigurationSource;
import org.springframework.web.cors.UrlBasedCorsConfigurationSource;

import java.io.InputStream;
import java.util.Arrays;
import java.util.concurrent.ConcurrentHashMap;
/*@DependsOn("keycloakConfigResolver")*/
@KeycloakConfiguration
@ConditionalOnProperty(name = "keycloak.enabled", havingValue = "true", matchIfMissing = true)
/*@Configuration*/
/*@EnableWebSecurity
@EnableGlobalMethodSecurity(jsr250Enabled = true)*/
public class KeycloakSecurityConfig extends KeycloakWebSecurityConfigurerAdapter {


    @Override
    protected void configure(HttpSecurity http) throws Exception {
        super.configure(http);
        http.sessionManagement()
                .sessionAuthenticationStrategy(sessionAuthenticationStrategy()).and().addFilterBefore(keycloakAuthenticationProcessingFilter(),
                        X509AuthenticationFilter.class).exceptionHandling()
                .authenticationEntryPoint(authenticationEntryPoint()).authenticationEntryPoint(authenticationEntryPoint2())
                .and() .authorizeRequests().antMatchers("/tenant").hasAnyRole("user")
                .anyRequest()
                .permitAll();
        http.csrf().disable();
    }



    @Autowired
    public void configureGlobal(AuthenticationManagerBuilder auth) throws Exception {
        KeycloakAuthenticationProvider keycloakAuthenticationProvider = keycloakAuthenticationProvider();
        keycloakAuthenticationProvider.setGrantedAuthoritiesMapper(new SimpleAuthorityMapper());
        auth.authenticationProvider(keycloakAuthenticationProvider);

    }

    @Bean
    @Override
    protected SessionAuthenticationStrategy sessionAuthenticationStrategy() {
        return new RegisterSessionAuthenticationStrategy(new SessionRegistryImpl());
    }

    @Override
    protected AuthenticationEntryPoint authenticationEntryPoint() throws Exception {
        return new MultitenantKeycloakAuthenticationEntryPoint(adapterDeploymentContext());
    }

    protected AuthenticationEntryPoint authenticationEntryPoint2() throws Exception {
        return new MultitenantKeycloakAuthenticationEntryPoint(adapterDeploymentContext(), new AntPathRequestMatcher("/tenant/*/*"));
    }

    @Override
    protected KeycloakAuthenticationProcessingFilter keycloakAuthenticationProcessingFilter() throws Exception {
        KeycloakAuthenticationProcessingFilter filter = new KeycloakAuthenticationProcessingFilter(authenticationManager(), new AntPathRequestMatcher("/tenant/*/*"));
        filter.setSessionAuthenticationStrategy(sessionAuthenticationStrategy());
        return filter;
    }

    @SuppressWarnings({ "rawtypes", "unchecked" })
    @Bean
    public FilterRegistrationBean keycloakAuthenticationProcessingFilterRegistrationBean(KeycloakAuthenticationProcessingFilter filter) {
        FilterRegistrationBean registrationBean = new FilterRegistrationBean(filter);
        registrationBean.setEnabled(false);
        return registrationBean;
    }

    @SuppressWarnings({ "rawtypes", "unchecked" })
    @Bean
    public FilterRegistrationBean keycloakPreAuthActionsFilterRegistrationBean(KeycloakPreAuthActionsFilter filter) {
        FilterRegistrationBean registrationBean = new FilterRegistrationBean(filter);
        registrationBean.setEnabled(false);
        return registrationBean;
    }

    @SuppressWarnings({ "rawtypes", "unchecked" })
    @Bean
    public FilterRegistrationBean keycloakAuthenticatedActionsFilterBean(KeycloakAuthenticatedActionsFilter filter) {
        FilterRegistrationBean registrationBean = new FilterRegistrationBean(filter);
        registrationBean.setEnabled(false);
        return registrationBean;
    }

    @SuppressWarnings({ "rawtypes", "unchecked" })
    @Bean
    public FilterRegistrationBean keycloakSecurityContextRequestFilterBean(KeycloakSecurityContextRequestFilter filter) {
        FilterRegistrationBean registrationBean = new FilterRegistrationBean(filter);
        registrationBean.setEnabled(false);
        return registrationBean;
    }

    @Bean
    public CorsConfigurationSource corsConfigurationSource() {
        CorsConfiguration configuration = new CorsConfiguration();
        configuration.setAllowedOrigins(Arrays.asList("*"));
        configuration.setAllowedMethods(Arrays.asList(HttpMethod.OPTIONS.name(), "GET", "POST"));
        configuration.setAllowedHeaders(Arrays.asList("Access-Control-Allow-Headers", "Access-Control-Allow-Origin", "Authorization"));
        UrlBasedCorsConfigurationSource source = new UrlBasedCorsConfigurationSource();
        source.registerCorsConfiguration("/**", configuration);
        return source;
    }


   /*@Bean
    public KeycloakConfigResolver keycloakConfigResolver() {
        return new KeycloakSpringBootConfigResolver();
    }*/
   @Bean
   @Autowired
   @ConditionalOnMissingBean(PathBasedConfigurer.class)
   public KeycloakConfigResolver keycloakConfigResolver() {
       return new PathBasedConfigurer();
   }


}

**Comment by AasthaSethia** [comment]
I will upload my code on github and share the link with you thank you so much for your help

**Comment by AasthaSethia** [comment]
https://github.com/AasthaSethia/multitenancy
